# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["m1.py",
           "m1_copy.py"]

doc_url = "https://thakkarparth007.github.io/nbdev_all_demo/"

git_url = "https://github.com/thakkarparth007/nbdev_all_demo/tree/master/"

def custom_doc_links(name): return None
