# AUTOGENERATED! DO NOT EDIT! File to edit: m1.ipynb (unless otherwise specified).

__all__ = []

# Cell

#export
import math as math1

#nbdev_comment _all_ = ['math1']

# Cell

print("m1 loaded, pi=", math1.pi)