# AUTOGENERATED! DO NOT EDIT! File to edit: m1_copy.ipynb (unless otherwise specified).

__all__ = []

# Cell

#export
import math as math2

#nbdev_comment _all_ = ['math2']

# Cell

print("m1_copy loaded, pi=", math2.pi)
print("This is added directly in m1_copy.py")